INSERT INTO perfumum_manuscripts 
    (manuscript_id, title, language, date_range, repository, region, license, scan_url, ocr_status, tags, axis_id)
  VALUES
    (
      'MS_0001',
      'Recettes olfactives — cahier 1 (seed)',
      'Sanskrit',
      '1700-1800',
      'Bibliothèque (seed)',
      'China',
      'All-rights-reserved',
      NULL,
      'needs_review',
      '["incense","resins","trade"]',
      'AX2_ETHNOBOTANY_COMP'
    ),
    (
      'MS_0002',
      'Recettes olfactives — cahier 2 (seed)',
      'Sanskrit',
      '1200-1300',
      'Bibliothèque (seed)',
      'China',
      'All-rights-reserved',
      NULL,
      'queued',
      '["incense","resins","trade"]',
      'AX2_ETHNOBOTANY_COMP'
    ),
    (
      'MS_0003',
      'Recettes olfactives — cahier 3 (seed)',
      'Sanskrit',
      '1600-1700',
      'Archive privée (seed)',
      'China',
      'CC-BY',
      NULL,
      'done',
      '["incense","resins","trade"]',
      'AX2_ETHNOBOTANY_COMP'
    ),
    (
      'MS_0004',
      'Recettes olfactives — cahier 4 (seed)',
      'Classical Chinese',
      '1600-1700',
      'Bibliothèque (seed)',
      'India',
      'CC-BY',
      NULL,
      'needs_review',
      '["incense","resins","trade"]',
      'AX2_ETHNOBOTANY_COMP'
    ),
    (
      'MS_0005',
      'Recettes olfactives — cahier 5 (seed)',
      'Sanskrit',
      '1200-1300',
      'Topkapi Palace Library',
      'China',
      'CC-BY',
      NULL,
      'queued',
      '["incense","resins","trade"]',
      'AX2_ETHNOBOTANY_COMP'
    ),
    (
      'MS_0006',
      'Recettes olfactives — cahier 6 (seed)',
      'Arabic',
      '1200-1300',
      'Archive privée (seed)',
      'India',
      'Unknown',
      NULL,
      'needs_review',
      '["incense","resins","trade"]',
      'AX2_ETHNOBOTANY_COMP'
    ),
    (
      'MS_0007',
      'Recettes olfactives — cahier 7 (seed)',
      'Spanish',
      '1700-1800',
      'Topkapi Palace Library',
      'Mediterranean',
      'Unknown',
      NULL,
      'needs_review',
      '["incense","resins","trade"]',
      'AX2_ETHNOBOTANY_COMP'
    ),
    (
      'MS_0008',
      'Recettes olfactives — cahier 8 (seed)',
      'Ottoman Turkish',
      '1200-1300',
      'Topkapi Palace Library',
      'Colombia',
      'All-rights-reserved',
      NULL,
      'needs_review',
      '["incense","resins","trade"]',
      'AX2_ETHNOBOTANY_COMP'
    ),
    (
      'MS_0009',
      'Recettes olfactives — cahier 9 (seed)',
      'Sanskrit',
      '1500-1600',
      'Bibliothèque (seed)',
      'Ottoman',
      'CC-BY',
      NULL,
      'queued',
      '["incense","resins","trade"]',
      'AX2_ETHNOBOTANY_COMP'
    ),
    (
      'MS_0010',
      'Recettes olfactives — cahier 10 (seed)',
      'Ottoman Turkish',
      '1500-1600',
      'Bibliothèque (seed)',
      'India',
      'CC-BY',
      NULL,
      'done',
      '["incense","resins","trade"]',
      'AX2_ETHNOBOTANY_COMP'
    )
  ON DUPLICATE KEY UPDATE
    title = VALUES(title),
    language = VALUES(language),
    date_range = VALUES(date_range),
    repository = VALUES(repository),
    region = VALUES(region),
    license = VALUES(license),
    scan_url = VALUES(scan_url),
    ocr_status = VALUES(ocr_status),
    tags = VALUES(tags);