INSERT INTO text_fragments 
    (fragment_id, manuscript_id, language, original_text, translation_fr, translation_en, entities, evidence_level, notes, axis_id)
  VALUES
    (
      'FRAG_0001',
      'MS_0006',
      'mixed',
      '...',
      '...',
      NULL,
      '[{"type": "plant", "value": "Cistus", "confidence": 0.47}]',
      'probable',
      'seed',
      'AX2_ETHNOBOTANY_COMP'
    ),
    (
      'FRAG_0002',
      'MS_0004',
      'mixed',
      '...',
      '...',
      NULL,
      '[{"type": "plant", "value": "Boswellia", "confidence": 0.46}]',
      'hypothetical',
      'seed',
      'AX2_ETHNOBOTANY_COMP'
    ),
    (
      'FRAG_0003',
      'MS_0002',
      'mixed',
      '...',
      '...',
      NULL,
      '[{"type": "plant", "value": "Citrus", "confidence": 0.61}]',
      'probable',
      'seed',
      'AX2_ETHNOBOTANY_COMP'
    ),
    (
      'FRAG_0004',
      'MS_0008',
      'mixed',
      '...',
      '...',
      NULL,
      '[{"type": "plant", "value": "Copaifera", "confidence": 0.72}]',
      'hypothetical',
      'seed',
      'AX2_ETHNOBOTANY_COMP'
    ),
    (
      'FRAG_0005',
      'MS_0005',
      'mixed',
      '...',
      '...',
      NULL,
      '[{"type": "plant", "value": "Boswellia", "confidence": 0.55}]',
      'hypothetical',
      'seed',
      'AX2_ETHNOBOTANY_COMP'
    ),
    (
      'FRAG_0006',
      'MS_0003',
      'mixed',
      '...',
      '...',
      NULL,
      '[{"type": "plant", "value": "Boswellia", "confidence": 0.86}]',
      'hypothetical',
      'seed',
      'AX2_ETHNOBOTANY_COMP'
    ),
    (
      'FRAG_0007',
      'MS_0002',
      'mixed',
      '...',
      '...',
      NULL,
      '[{"type": "plant", "value": "Copaifera", "confidence": 0.78}]',
      'probable',
      'seed',
      'AX2_ETHNOBOTANY_COMP'
    ),
    (
      'FRAG_0008',
      'MS_0003',
      'mixed',
      '...',
      '...',
      NULL,
      '[{"type": "plant", "value": "Commiphora", "confidence": 0.9}]',
      'hypothetical',
      'seed',
      'AX2_ETHNOBOTANY_COMP'
    ),
    (
      'FRAG_0009',
      'MS_0002',
      'mixed',
      '...',
      '...',
      NULL,
      '[{"type": "plant", "value": "Citrus", "confidence": 0.85}]',
      'hypothetical',
      'seed',
      'AX2_ETHNOBOTANY_COMP'
    ),
    (
      'FRAG_0010',
      'MS_0010',
      'mixed',
      '...',
      '...',
      NULL,
      '[{"type": "plant", "value": "Cistus", "confidence": 0.75}]',
      'probable',
      'seed',
      'AX2_ETHNOBOTANY_COMP'
    ),
    (
      'FRAG_0011',
      'MS_0002',
      'mixed',
      '...',
      '...',
      NULL,
      '[{"type": "plant", "value": "Citrus", "confidence": 0.87}]',
      'probable',
      'seed',
      'AX2_ETHNOBOTANY_COMP'
    ),
    (
      'FRAG_0012',
      'MS_0004',
      'mixed',
      '...',
      '...',
      NULL,
      '[{"type": "plant", "value": "Boswellia", "confidence": 0.9}]',
      'probable',
      'seed',
      'AX2_ETHNOBOTANY_COMP'
    ),
    (
      'FRAG_0013',
      'MS_0010',
      'mixed',
      '...',
      '...',
      NULL,
      '[{"type": "plant", "value": "Boswellia", "confidence": 0.69}]',
      'probable',
      'seed',
      'AX2_ETHNOBOTANY_COMP'
    ),
    (
      'FRAG_0014',
      'MS_0003',
      'mixed',
      '...',
      '...',
      NULL,
      '[{"type": "plant", "value": "Boswellia", "confidence": 0.78}]',
      'hypothetical',
      'seed',
      'AX2_ETHNOBOTANY_COMP'
    ),
    (
      'FRAG_0015',
      'MS_0008',
      'mixed',
      '...',
      '...',
      NULL,
      '[{"type": "plant", "value": "Cistus", "confidence": 0.71}]',
      'hypothetical',
      'seed',
      'AX2_ETHNOBOTANY_COMP'
    ),
    (
      'FRAG_0016',
      'MS_0009',
      'mixed',
      '...',
      '...',
      NULL,
      '[{"type": "plant", "value": "Commiphora", "confidence": 0.65}]',
      'probable',
      'seed',
      'AX2_ETHNOBOTANY_COMP'
    ),
    (
      'FRAG_0017',
      'MS_0007',
      'mixed',
      '...',
      '...',
      NULL,
      '[{"type": "plant", "value": "Citrus", "confidence": 0.73}]',
      'hypothetical',
      'seed',
      'AX2_ETHNOBOTANY_COMP'
    ),
    (
      'FRAG_0018',
      'MS_0007',
      'mixed',
      '...',
      '...',
      NULL,
      '[{"type": "plant", "value": "Copaifera", "confidence": 0.81}]',
      'hypothetical',
      'seed',
      'AX2_ETHNOBOTANY_COMP'
    ),
    (
      'FRAG_0019',
      'MS_0006',
      'mixed',
      '...',
      '...',
      NULL,
      '[{"type": "plant", "value": "Commiphora", "confidence": 0.52}]',
      'hypothetical',
      'seed',
      'AX2_ETHNOBOTANY_COMP'
    ),
    (
      'FRAG_0020',
      'MS_0003',
      'mixed',
      '...',
      '...',
      NULL,
      '[{"type": "plant", "value": "Commiphora", "confidence": 0.53}]',
      'probable',
      'seed',
      'AX2_ETHNOBOTANY_COMP'
    )
  ON DUPLICATE KEY UPDATE
    manuscript_id = VALUES(manuscript_id),
    language = VALUES(language),
    original_text = VALUES(original_text),
    translation_fr = VALUES(translation_fr),
    entities = VALUES(entities),
    evidence_level = VALUES(evidence_level),
    notes = VALUES(notes);