/**
 * Script d'insertion des nouvelles références bibliographiques
 * Sources : Batch 1 (notes_pdfs_perfumum.md), Batch 2 (analyse_sources_perfumum_session2.md), Batch 3 (analyse_sources_perfumum_batch3.md)
 */
import mysql from 'mysql2/promise';

const conn = await mysql.createConnection(process.env.DATABASE_URL);

const references = [
  // ============ BATCH 1 ============
  {
    entry_key: 'turin-yoshii-2002-sor',
    entry_type: 'article',
    title: 'Structure-Odor Relations: A Modern Perspective',
    authors: 'Turin, Luca; Yoshii, Fumiko',
    year: 2002,
    container_title: 'Handbook of Olfaction and Gustation',
    doi: null,
    url: null,
    axis_primary_code: 'A1 Smell studies & critical theory',
    notes: 'Revue critique des relations structure-odeur (SOR). Théorie vibratoire de Turin. Cas d\'anosmie spécifique : Galaxolide (MW 244), Ambrox (MW 236), Karanal. Résolution infinie du système olfactif humain.',
    tags: JSON.stringify(['SOR', 'structure-odeur', 'anosmie', 'théorie vibratoire', 'Turin', 'muscs']),
    relevance_score: 4,
    read_status: 'read',
    pack_version: 'batch1'
  },

  // ============ BATCH 2 ============
  {
    entry_key: 'davis-thys-senocak-2017-istanbul',
    entry_type: 'article',
    title: 'Heritage and Scent: Research and Exhibition of Istanbul\'s Changing Smellscapes',
    authors: 'Davis, L.; Thys-Şenocak, L.',
    year: 2017,
    container_title: 'International Journal of Heritage Studies',
    doi: '10.1080/13527258.2017.1290757',
    url: null,
    axis_primary_code: 'C3 Global scent histories beyond Eurocentrism',
    notes: 'Smellscape patrimonial du Marché aux Épices d\'Istanbul (Mısır Çarşısı, 1661-1665). Matières historiques : musc, ambre gris, eau de rose, camphre, encens. Méthodes : smellwalks, cartographie olfactive, ateliers participatifs. Notion de buhurcı (parfumeur officiel ottoman).',
    tags: JSON.stringify(['smellscape', 'Istanbul', 'patrimoine', 'musc', 'ambre gris', 'Ottoman', 'musée']),
    relevance_score: 4,
    read_status: 'read',
    pack_version: 'batch2'
  },
  {
    entry_key: 'verbeek-2021-museum-scent',
    entry_type: 'article',
    title: 'How Can Scents Enhance the Impact of Guided Museum Tours? Towards an Impact Approach for Olfactory Museology',
    authors: 'Verbeek, Caro et al.',
    year: 2021,
    container_title: 'The Senses and Society',
    doi: null,
    url: null,
    axis_primary_code: 'B1 Olfactory art & aesthetics',
    notes: 'Six fonctions de l\'odeur en muséologie (Banes) : illustrer, évoquer, compléter/contraster, convoquer souvenirs, ritualiser, distancier. Osmothèque de Paris comme archive de référence. Bibliographie fondamentale : Drobnick, Classen, Spence, Stevenson.',
    tags: JSON.stringify(['muséologie', 'Odeuropa', 'musée', 'patrimoine olfactif', 'Verbeek', 'Osmothèque']),
    relevance_score: 5,
    read_status: 'read',
    pack_version: 'batch2'
  },
  {
    entry_key: 'boswell-2011-intangible-heritage',
    entry_type: 'article',
    title: 'Challenges to Sustaining Intangible Cultural Heritage',
    authors: 'Boswell, Rosabelle',
    year: 2011,
    container_title: 'Heritage & Society',
    doi: null,
    url: null,
    axis_primary_code: 'A1 Smell studies & critical theory',
    notes: 'Critique de la Convention UNESCO 2003 sur le PCI. Instrumentalisation par les États. Tension documentation vs transmission vivante. Zanzibar : odeur, identité locale et patrimoine immatériel. Gouvernance du patrimoine olfactif.',
    tags: JSON.stringify(['PCI', 'UNESCO', 'patrimoine immatériel', 'gouvernance', 'décolonial', 'Zanzibar']),
    relevance_score: 3,
    read_status: 'read',
    pack_version: 'batch2'
  },
  {
    entry_key: 'edreva-tobacco-valeric-acid',
    entry_type: 'article',
    title: 'Evaluation of Aroma in Oriental Tobaccos as Based on Valeric Acid Gas Chromatography',
    authors: 'Edreva, A. et al.',
    year: null,
    container_title: 'Beiträge zur Tabakforschung International',
    doi: null,
    url: null,
    axis_primary_code: 'N1 Tabac: ethnobotanique & rituels',
    notes: 'Acide isovalérique et acide 3-méthylvalérique comme marqueurs discriminants tabacs orientaux (Izmir, Samsun) vs Virginia/Burley. Corrélation statistique acide isovalérique → score arôme. Précurseurs : sucrose esters de surface foliaire.',
    tags: JSON.stringify(['tabac oriental', 'Izmir', 'Samsun', 'acide isovalérique', 'GC', 'arôme tabac', 'marqueurs chimiques']),
    relevance_score: 5,
    read_status: 'read',
    pack_version: 'batch2'
  },
  {
    entry_key: 'jiang-2020-picea-brachytyla',
    entry_type: 'article',
    title: 'Structurally Diverse Terpenoids from the Twigs and Needles of the Endangered Plant Picea brachytyla',
    authors: 'Jiang, et al.',
    year: 2020,
    container_title: 'Phytochemistry',
    doi: null,
    url: null,
    axis_primary_code: 'Biotech / Conservation substitutes',
    notes: 'Picea brachytyla (épicéa de Sargent), endémique de Chine, IUCN menacée. 7 nouveaux sesquiterpènes et diterpènes : brachytylols A-C, labdanes. β-Caryophyllène, α-Pinène, β-Pinène dans aiguilles. Activités cytotoxiques et anti-inflammatoires.',
    tags: JSON.stringify(['Picea brachytyla', 'conifère menacé', 'sesquiterpènes', 'brachytylol', 'Chine', 'IUCN', 'phytochimie']),
    relevance_score: 4,
    read_status: 'read',
    pack_version: 'batch2'
  },
  {
    entry_key: 'embo-scent-of-life-2007',
    entry_type: 'article',
    title: 'The Scent of Life: The Exquisite Complexity of the Sense of Smell in Animals and Humans',
    authors: 'Malnic, Bettina et al.',
    year: 2007,
    container_title: 'EMBO Reports',
    doi: null,
    url: null,
    axis_primary_code: 'A1 Smell studies & critical theory',
    notes: '350-400 récepteurs olfactifs (OR), codage combinatoire, carte olfactive dans le bulbe olfactif. Controverse théorie de forme vs théorie vibratoire (Turin 1996). Système Gαolf-Ric-8B pour expression hétérologue des OR.',
    tags: JSON.stringify(['neurobiologie', 'récepteurs olfactifs', 'codage combinatoire', 'bulbe olfactif', 'Nobel 2004', 'Buck', 'Axel']),
    relevance_score: 3,
    read_status: 'read',
    pack_version: 'batch2'
  },
  {
    entry_key: 'ajaiyeoba-ekundayo-1999-aframomum',
    entry_type: 'article',
    title: 'Essential Oil Constituents of Aframomum melegueta (Roscoe) K. Schum. Seeds',
    authors: 'Ajaiyeoba, E.O.; Ekundayo, O.',
    year: 1999,
    container_title: 'Flavour and Fragrance Journal',
    doi: '10.1002/(SICI)1099-1026(199903/04)14:2<109::AID-FFJ793>3.0.CO;2-7',
    url: null,
    axis_primary_code: 'N3 Psychoactive ethnobotany (context only)',
    notes: 'Aframomum melegueta (poivre de Guinée, grains de paradis). Huile essentielle dominée par α-humulène (28.1%), β-caryophyllène (22.4%), oxyde de caryophyllène (21.3%), humulénol II (19.8%). Variabilité chimio-géographique Nigeria vs Cameroun. Connexion moléculaire avec houblon et cannabis.',
    tags: JSON.stringify(['Aframomum melegueta', 'grains de paradis', 'α-humulène', 'β-caryophyllène', 'Afrique de l\'Ouest', 'GC-MS', 'variabilité géographique']),
    relevance_score: 5,
    read_status: 'read',
    pack_version: 'batch2'
  },
  {
    entry_key: 'bembibre-strlic-2021-glam-guidelines',
    entry_type: 'report',
    title: 'Guidelines on the Use of Smells in GLAMs',
    authors: 'Bembibre, Cecilia; Strlic, Matija',
    year: 2021,
    container_title: 'Odeuropa Deliverable D6.1',
    doi: null,
    url: 'https://odeuropa.eu',
    axis_primary_code: 'B1 Olfactory art & aesthetics',
    notes: 'Barrières à l\'utilisation des odeurs dans musées/bibliothèques/archives/galeries (GLAMs). 4 catégories : expérience visiteur, design olfactif, interprétation/curation, conservation. 30 professionnels interrogés. Matrice barrières-solutions directement transposable à PERFUMUM.',
    tags: JSON.stringify(['Odeuropa', 'GLAM', 'muséologie', 'barrières', 'UCL', 'patrimoine olfactif', 'COV']),
    relevance_score: 4,
    read_status: 'read',
    pack_version: 'batch2'
  },
  {
    entry_key: 'odeuropa-2022-scent-collection',
    entry_type: 'report',
    title: 'Historical Scent Collection Booklet',
    authors: 'Odeuropa',
    year: 2022,
    container_title: 'Odeuropa / LMR Naturals / Givaudan',
    doi: null,
    url: 'https://odeuropa.eu',
    axis_primary_code: 'Heritage science / Lost perfumes',
    notes: '12 reconstitutions olfactives historiques (XVe-XIXe s.). Pomander (Ulm, 1516) : lavande, romarin, muscade, clou de girofle, civette, musc, ambre gris. Myrrhe (XVe s.). Amsterdam (XVIIe s.). Méthodologie : sources → composition → parfumeur → documentation.',
    tags: JSON.stringify(['Odeuropa', 'reconstitution', 'parfum historique', 'Pomander', 'Amsterdam', 'myrrhe', 'LMR Naturals']),
    relevance_score: 5,
    read_status: 'read',
    pack_version: 'batch2'
  },
  {
    entry_key: 'ehrich-2023-olfactory-storytelling-toolkit',
    entry_type: 'book',
    title: 'The Olfactory Storytelling Toolkit: A "How-To" Guide for Working with Smells in Museums and Heritage Institutions',
    authors: 'Ehrich, Sofia Collette; Leemans, Inger; Bembibre, Cecilia; Tullett, William; Verbeek, Caro; Alexopoulos, Georgios; Marx, Lizzie',
    year: 2023,
    container_title: 'Odeuropa / Zenodo',
    doi: '10.5281/zenodo.7848362',
    url: 'https://doi.org/10.5281/zenodo.7848362',
    axis_primary_code: 'B1 Olfactory art & aesthetics',
    notes: 'Guide pratique 235 pages pour musées. 4 sections : curation récits olfactifs, développement odeurs patrimoniales, design événements olfactifs, évaluation risques. 6 études de cas. Nose-First Art Historical Odour Wheel. Smell Explorer Odeuropa. Smell manifestos (Plailly, Le Guérer).',
    tags: JSON.stringify(['Odeuropa', 'muséologie', 'toolkit', 'Zenodo', 'Creative Commons', 'protocole', 'Nose-First']),
    relevance_score: 5,
    read_status: 'read',
    pack_version: 'batch2'
  },

  // ============ BATCH 3 ============
  {
    entry_key: 'russo-2021-cannabis-sulfur-compounds',
    entry_type: 'article',
    title: 'Identification of a New Family of Prenylated Volatile Sulfur Compounds in Cannabis Revealed by Comprehensive Two-Dimensional Gas Chromatography',
    authors: 'Russo, Ethan B. et al.',
    year: 2021,
    container_title: 'ACS Omega',
    doi: '10.1021/acsomega.1c04196',
    url: null,
    axis_primary_code: 'M1 Cannabis: diversité colombienne (chimio/terpènes)',
    notes: '3-méthyl-2-butène-1-thiol (prenylthiol) = composé skunk principal du cannabis. GC×GC-TOFMS. Concentration ppb mais seuil olfactif < 1 ppb. Famille chimique : composés soufrés volatils prénylés (VSC). Marqueurs olfactifs ultra-puissants.',
    tags: JSON.stringify(['cannabis', 'composés soufrés', 'prenylthiol', 'skunk', 'GC×GC-TOFMS', 'VSC', 'ACS Omega']),
    relevance_score: 5,
    read_status: 'read',
    pack_version: 'batch3'
  },
  {
    entry_key: 'paeonia-tps-2023',
    entry_type: 'article',
    title: 'Identification and Characterization of Terpene Synthase Genes Accounting for Volatile Terpene Emissions in the Flower of Paeonia lactiflora',
    authors: 'Unknown',
    year: 2023,
    container_title: 'Unknown',
    doi: null,
    url: null,
    axis_primary_code: 'Taxonomy & distribution',
    notes: 'Paeonia lactiflora (pivoine). Gènes TPS : PlTPS1, PlTPS2, PlTPS3. Composés dominants : linalol, β-ocimène, germacrène D, β-caryophyllène. Accord pivoine = linalol + β-ocimène + hexenol. Approche génomique-métabolomique.',
    tags: JSON.stringify(['pivoine', 'Paeonia lactiflora', 'terpène synthase', 'linalol', 'β-ocimène', 'germacrène D', 'génomique']),
    relevance_score: 4,
    read_status: 'read',
    pack_version: 'batch3'
  },
  {
    entry_key: 'capsicum-terpene-genomics-2025',
    entry_type: 'article',
    title: 'Genome-Wide Identification of Terpenoid Metabolism Pathway Genes in Chili and Screening of Key Regulatory Genes for Fruit Terpenoid Aroma Components',
    authors: 'Unknown',
    year: 2025,
    container_title: 'Horticulturae',
    doi: null,
    url: null,
    axis_primary_code: 'Taxonomy & distribution',
    notes: 'Capsicum annuum. 67 gènes voie terpénoïde. Variété HDL : α-calacorène, α-cubène, cis-β-farnésène. Variété GLD608 : linalol, nérolidol. Enzymes clés : CaHMGS-3, CaMVD-1 (linalol), CaTPS-5 (nérolidol). Variabilité intra-espèce.',
    tags: JSON.stringify(['piment', 'Capsicum annuum', 'terpène', 'génomique', 'linalol', 'nérolidol', 'variabilité intra-espèce']),
    relevance_score: 4,
    read_status: 'read',
    pack_version: 'batch3'
  },
  {
    entry_key: 'frankincense-myrrh-synergy',
    entry_type: 'article',
    title: 'Seeing the Unseen of the Combination of Two Natural Resins, Frankincense and Myrrh: Changes in Chemical Constituents and Pharmacological Activities',
    authors: 'Unknown',
    year: null,
    container_title: 'Unknown',
    doi: null,
    url: null,
    axis_primary_code: 'Heritage science / Lost perfumes',
    notes: 'Boswellia sacra + Commiphora myrrha combinés. Synergies moléculaires : acide boswellique, furanosesquiterpènes, incensole acétate. Nouveaux composés émergent par réaction chimique. Légitime scientifiquement la notion d\'accord olfactif comme phénomène chimique réel.',
    tags: JSON.stringify(['oliban', 'myrrhe', 'Boswellia sacra', 'Commiphora myrrha', 'accord résine', 'synergies moléculaires', 'médecine chinoise']),
    relevance_score: 4,
    read_status: 'read',
    pack_version: 'batch3'
  },
  {
    entry_key: 'encapsulation-fragrances-polymers',
    entry_type: 'article',
    title: 'Encapsulation of Flavours and Fragrances into Polymers',
    authors: 'Unknown',
    year: null,
    container_title: 'Unknown',
    doi: null,
    url: null,
    axis_primary_code: 'Digital smell / Applied',
    notes: 'Encapsulation de composés aromatiques dans matrices polymériques. Technologies : coacervation, polymérisation interfaciale, β-cyclodextrine. Applications : parfumerie, alimentation, textiles. Cinétiques de libération, paramètres logP. Lien avec protocoles beurre de cacao PERFUMUM.',
    tags: JSON.stringify(['encapsulation', 'cyclodextrine', 'libération contrôlée', 'coacervation', 'parfumerie', 'logP', 'beurre de cacao']),
    relevance_score: 3,
    read_status: 'read',
    pack_version: 'batch3'
  },
  {
    entry_key: 'profragrances-pseudorotaxanes-2021',
    entry_type: 'article',
    title: 'Mechanically Interlocked Profragrances for the Controlled Release of Scents',
    authors: 'Unknown',
    year: 2021,
    container_title: 'Journal of Organic Chemistry',
    doi: null,
    url: null,
    axis_primary_code: 'Digital smell / Applied',
    notes: 'Profragrances mécaniquement entrelacées ([2]pseudorotaxanes). Libération thermique ou enzymatique. Modulation précise de la température de libération. Concept de prodrogue olfactive. Pertinent pour la pyrolyse tabac : précurseurs non volatils → arômes.',
    tags: JSON.stringify(['profragrance', 'pseudorotaxane', 'libération contrôlée', 'pyrolyse', 'chimie organique', 'prodrogue olfactive']),
    relevance_score: 3,
    read_status: 'read',
    pack_version: 'batch3'
  },
  {
    entry_key: 'chinese-cigar-hs-spme-gchrms',
    entry_type: 'article',
    title: 'Analysis of Different Cultivars and Origins of Chinese Cigar Tobacco Leaves Based on HS-SPME-GC-HRMS Combined with Multivariate Statistical Methods',
    authors: 'Unknown',
    year: null,
    container_title: 'Unknown',
    doi: null,
    url: null,
    axis_primary_code: 'N1 Tabac: ethnobotanique & rituels',
    notes: 'Tabacs cigares chinois par HS-SPME-GC-HRMS + PCA/OPLS-DA. Marqueurs discriminants : β-damascénone, β-ionone (norisoprénoïdes), eugénol, isoeugénol, nornicotine. Différenciation terroirs tabacoles par profil moléculaire.',
    tags: JSON.stringify(['tabac cigare', 'Chine', 'GC-HRMS', 'β-damascénone', 'β-ionone', 'norisoprénoïdes', 'PCA', 'terroir tabac']),
    relevance_score: 4,
    read_status: 'read',
    pack_version: 'batch3'
  },
  {
    entry_key: 'tobacco-carotenoid-volatiles',
    entry_type: 'article',
    title: 'Carotenoid-Related Volatile Compounds of Tobacco (Nicotiana tabacum L.) Essential Oils',
    authors: 'Unknown',
    year: null,
    container_title: 'Unknown',
    doi: null,
    url: null,
    axis_primary_code: 'N1 Tabac: ethnobotanique & rituels',
    notes: 'Caroténoïdes tabac (β-carotène, lutéine, zéaxanthine) → dégradation séchage/fermentation → norisoprénoïdes : β-damascénone, β-ionone, dihydroactinidiolide, mégastigmatrienone. Notes florales-fruitées-mielleuses des tabacs de qualité. Chaîne causale complète caroténoïde → arôme.',
    tags: JSON.stringify(['tabac', 'caroténoïdes', 'norisoprénoïdes', 'β-damascénone', 'β-ionone', 'fermentation', 'pyrolyse', 'transformation moléculaire']),
    relevance_score: 5,
    read_status: 'read',
    pack_version: 'batch3'
  },
  {
    entry_key: 'tobacco-phenolic-compounds',
    entry_type: 'article',
    title: 'Phenolic Compound Formation in Tobacco',
    authors: 'Unknown',
    year: null,
    container_title: 'Unknown',
    doi: null,
    url: null,
    axis_primary_code: 'N1 Tabac: ethnobotanique & rituels',
    notes: 'Formation composés phénoliques tabac post-récolte. Acide chlorogénique, rutine, scopoline, solanesol. Voie pyrolytique : acide chlorogénique → guaïacol → phénol. Notes fumées-phénolées des tabacs orientaux.',
    tags: JSON.stringify(['tabac', 'phénols', 'acide chlorogénique', 'guaïacol', 'pyrolyse', 'fumée', 'tabac oriental']),
    relevance_score: 4,
    read_status: 'read',
    pack_version: 'batch3'
  },
  {
    entry_key: 'samsun-genetic-ssrmarkers',
    entry_type: 'article',
    title: 'Genetic Variations in Samsun Tobacco Lines',
    authors: 'Saygili, Ibrahim et al.',
    year: null,
    container_title: 'Unknown',
    doi: null,
    url: null,
    axis_primary_code: 'N1 Tabac: ethnobotanique & rituels',
    notes: '28 lignées tabac Samsun (Turquie). 19 lignées génétiquement distinctes (SSR markers). Nicotine 0.76-1.16%, sucres réducteurs 6.7-14.2%, phénols 44.8-938.7 ppm. Lignées S4, S5, S14 les plus performantes.',
    tags: JSON.stringify(['Samsun', 'tabac oriental', 'génétique', 'SSR', 'Turquie', 'nicotine', 'variabilité']),
    relevance_score: 4,
    read_status: 'read',
    pack_version: 'batch3'
  },
  {
    entry_key: 'rhodiola-threats-trade',
    entry_type: 'article',
    title: 'Running Out of Time to Smell the Rose Roots: Reviewing Threats and Trade in Wild Rhodiola rosea L.',
    authors: 'Unknown',
    year: null,
    container_title: 'Unknown',
    doi: null,
    url: null,
    axis_primary_code: 'Biotech / Conservation substitutes',
    notes: 'Rhodiola rosea (rhodiole). Surexploitation dans habitats naturels (Sibérie, Himalaya, Alpes). CITES dans plusieurs pays. Composés olfactifs clés : géraniol, 1-octanol, rosaridin. Médecine adaptogène = récolte des rhizomes = mort de la plante.',
    tags: JSON.stringify(['Rhodiola rosea', 'plante menacée', 'CITES', 'surexploitation', 'géraniol', '1-octanol', 'adaptogène', 'Sibérie']),
    relevance_score: 5,
    read_status: 'read',
    pack_version: 'batch3'
  },
  {
    entry_key: 'nardostachys-gcms-antimicrobial',
    entry_type: 'article',
    title: 'GC-MS Analysis and Anti-Microbial Activities of Volatile Oil of Nardostachys jatamansi D.C. Rhizomes',
    authors: 'Singh, V.; Rana, N.; Ali, M.',
    year: null,
    container_title: 'Unknown',
    doi: null,
    url: null,
    axis_primary_code: 'Biotech / Conservation substitutes',
    notes: 'Nardostachys jatamansi (nard de l\'Himalaya). GC-MS rhizomes Haridwar (Inde). Composés dominants : jatamansone (valeranone), β-eudesmol, nardol, patchoulol. CITES Appendix II. Mentionné dans la Bible. Activités antimicrobiennes documentées.',
    tags: JSON.stringify(['Nardostachys jatamansi', 'nard', 'Himalaya', 'GC-MS', 'jatamansone', 'CITES', 'Bible', 'plante menacée']),
    relevance_score: 5,
    read_status: 'read',
    pack_version: 'batch3'
  },
  {
    entry_key: 'burkina-plantes-aromatiques-revue',
    entry_type: 'article',
    title: 'Revue des Plantes Médicinales à Potentiel Aromatique du Burkina Faso',
    authors: 'Unknown',
    year: null,
    container_title: 'Unknown',
    doi: null,
    url: null,
    axis_primary_code: 'N3 Psychoactive ethnobotany (context only)',
    notes: '84 plantes médicinales aromatiques du Burkina Faso, 44 familles botaniques. Composés dominants : caryophyllènes, pinènes, phytols, linalols, acide hexadécanoïque, cinéole, phellandrène. Famille Césalpiniaceae la plus représentée. Propriétés : anti-inflammatoire, antibactérien, antioxydant.',
    tags: JSON.stringify(['Burkina Faso', 'plantes aromatiques', 'Afrique', 'Césalpiniaceae', 'β-caryophyllène', 'ethnobotanique', 'GC-MS']),
    relevance_score: 5,
    read_status: 'read',
    pack_version: 'batch3'
  },
  {
    entry_key: 'nomadic-ecologies-coca-amazonie-2017',
    entry_type: 'article',
    title: 'Nomadic Ecologies: Plants, Embodied Knowledge, and Temporality in the Colombian Amazon',
    authors: 'Unknown',
    year: 2017,
    container_title: 'Boletín de Antropología',
    doi: null,
    url: null,
    axis_primary_code: 'N3 Psychoactive ethnobotany (context only)',
    notes: 'Usage rituel de la coca (Erythroxylon coca) par les Murui de l\'Amazonie colombienne. Approche non-anthropocentrique : plantes comme co-créatrices de savoirs territoriaux. Composés aromatiques coca : méthyl salicylate, trans-cinnamaldéhyde. Cadre théorique pour usages rituels et savoirs incorporés.',
    tags: JSON.stringify(['coca', 'Erythroxylon coca', 'Amazonie', 'Colombie', 'Murui', 'ethnobotanique', 'décolonial', 'savoir incorporé']),
    relevance_score: 4,
    read_status: 'read',
    pack_version: 'batch3'
  },
  {
    entry_key: 'kannauj-perfume-industry',
    entry_type: 'article',
    title: 'The Perfume Industry of Kannauj',
    authors: 'Unknown',
    year: null,
    container_title: 'Unknown',
    doi: null,
    url: null,
    axis_primary_code: 'C3 Global scent histories beyond Eurocentrism',
    notes: 'Kannauj (Inde), capitale mondiale de l\'attar. Cluster industriel de Marshall. Distillation deg-bhapka = tacit knowledge transmis de génération en génération. Santalum album (santal). Patrimoine culturel immatériel menacé par industrialisation.',
    tags: JSON.stringify(['Kannauj', 'attar', 'santal', 'Inde', 'deg-bhapka', 'PCI', 'parfumerie traditionnelle', 'cluster industriel']),
    relevance_score: 4,
    read_status: 'read',
    pack_version: 'batch3'
  },
  {
    entry_key: 'industrial-fragrance-chemistry-history',
    entry_type: 'article',
    title: 'Industrial Fragrance Chemistry: A Brief Historical Overview',
    authors: 'Unknown',
    year: null,
    container_title: 'Unknown',
    doi: null,
    url: null,
    axis_primary_code: 'A1 Smell studies & critical theory',
    notes: 'Développement chimie industrielle des fragrances : distillation artisanale XIXe → synthèse chimique moderne. Isolement premiers composés (géraniol, linalol, citronellol) depuis huiles essentielles. Muscs synthétiques et aldéhydes. Dates de première synthèse des molécules clés.',
    tags: JSON.stringify(['histoire parfumerie', 'synthèse chimique', 'géraniol', 'linalol', 'muscs synthétiques', 'aldéhydes', 'Grasse']),
    relevance_score: 3,
    read_status: 'read',
    pack_version: 'batch3'
  },
  {
    entry_key: 'futurism-olfactory-verbeek',
    entry_type: 'article',
    title: 'In Search of Lost Scents: The Olfactory Dimension of Futurism',
    authors: 'Verbeek, Caro',
    year: null,
    container_title: 'Unknown',
    doi: null,
    url: null,
    axis_primary_code: 'B1 Olfactory art & aesthetics',
    notes: 'Dimension olfactive du Futurisme italien (1909-1942). Marinetti et les Futuristes : huile de moteur, essence, poudre à canon. Rupture avec le passé, vitesse, modernité. Précurseurs de l\'art olfactif contemporain. Cadre pour formaliser les Olfactory Experiences (od:L13 NOSE).',
    tags: JSON.stringify(['Futurisme', 'Marinetti', 'art olfactif', 'patrimoine artistique', 'Verbeek', 'Odeuropa', 'Atlas Mnémosyne']),
    relevance_score: 4,
    read_status: 'read',
    pack_version: 'batch3'
  },
  {
    entry_key: 'scent-sensibility-perception-shifts',
    entry_type: 'article',
    title: 'Scent and Sensibility: Perception Shifts in the Olfactory Domain',
    authors: 'Unknown',
    year: null,
    container_title: 'Unknown',
    doi: null,
    url: null,
    axis_primary_code: 'A1 Smell studies & critical theory',
    notes: 'Changements historiques de perception olfactive. Théories de la "civilisation des odeurs" (Corbin). Hiérarchies sensorielles et mutations du goût olfactif occidental XVIIe-XXe siècle. Mêmes molécules perçues différemment selon contextes.',
    tags: JSON.stringify(['perception olfactive', 'histoire', 'Corbin', 'civilisation des odeurs', 'hiérarchie sensorielle', 'culture']),
    relevance_score: 3,
    read_status: 'read',
    pack_version: 'batch3'
  },
  {
    entry_key: 'herrmann-2017-natural-profragrances-chimia',
    entry_type: 'article',
    title: 'Natural Profragrances: Glycosidic Precursors and Controlled Release',
    authors: 'Herrmann, Andreas',
    year: 2017,
    container_title: 'Chimia',
    doi: null,
    url: null,
    axis_primary_code: 'Digital smell / Applied',
    notes: 'Profragrances d\'origine naturelle. Précurseurs glycosidiques libèrent arômes par hydrolyse enzymatique. Firmenich. Glycosides aromatiques dans roses, raisins, tabac. Fermentation et dégradation enzymatique. Complète l\'article sur encapsulation et profragrances mécaniques.',
    tags: JSON.stringify(['profragrance', 'glycosides', 'hydrolyse enzymatique', 'Firmenich', 'Herrmann', 'libération contrôlée', 'fermentation']),
    relevance_score: 4,
    read_status: 'read',
    pack_version: 'batch3'
  },
  {
    entry_key: 'artificial-olfactory-memory-review',
    entry_type: 'article',
    title: 'From Materials to Applications: A Review of Research on Artificial Olfactory Memory',
    authors: 'Unknown',
    year: null,
    container_title: 'Unknown',
    doi: null,
    url: null,
    axis_primary_code: 'Digital smell / Hardware',
    notes: 'Nez électroniques, capteurs chimiques, réseaux de neurones artificiels pour reconnaissance d\'odeurs. Matériaux : polymères conducteurs, oxydes métalliques, MOFs. Perspectives pour caractérisation d\'odeurs patrimoniales et validation de reconstitutions.',
    tags: JSON.stringify(['nez électronique', 'capteurs chimiques', 'IA olfactive', 'MOF', 'polymères conducteurs', 'mémoire olfactive artificielle']),
    relevance_score: 3,
    read_status: 'read',
    pack_version: 'batch3'
  },
  {
    entry_key: 'wearable-olfactory-display-vr',
    entry_type: 'article',
    title: 'Extension of Wearable Olfactory Display for Multisensory VR Experience',
    authors: 'Unknown',
    year: null,
    container_title: 'Unknown',
    doi: null,
    url: null,
    axis_primary_code: 'Digital smell / Hardware',
    notes: 'Dispositif portable d\'affichage olfactif pour VR multisensorielle. Libération d\'odeurs synchronisées avec stimuli visuels et auditifs. Expériences immersives incluant la dimension olfactive. Cohérent avec travaux Odeuropa sur expositions muséales.',
    tags: JSON.stringify(['VR', 'réalité virtuelle', 'affichage olfactif', 'multisensoriel', 'restitution olfactive', 'muséologie']),
    relevance_score: 3,
    read_status: 'read',
    pack_version: 'batch3'
  },
  {
    entry_key: 'fermentation-aromatic-compounds',
    entry_type: 'article',
    title: 'Production of Aromatic Compounds by Microbial Fermentation',
    authors: 'Unknown',
    year: 2018,
    container_title: 'Fermentation',
    doi: null,
    url: null,
    axis_primary_code: 'N1 Tabac: ethnobotanique & rituels',
    notes: 'Production de composés aromatiques par fermentation microbienne. Levures, bactéries lactiques, moisissures. Voies métaboliques : esters, alcools supérieurs, acides gras, composés soufrés. Transformation fermentaire tabac, absolues fermentées, boissons aromatiques.',
    tags: JSON.stringify(['fermentation', 'arômes', 'levures', 'bactéries lactiques', 'esters', 'transformation moléculaire', 'tabac']),
    relevance_score: 3,
    read_status: 'read',
    pack_version: 'batch3'
  },
  {
    entry_key: 'pharmacie-globale-extraction-he',
    entry_type: 'article',
    title: 'Extraction des Huiles Aromatiques depuis des Surfaces Solides',
    authors: 'Unknown',
    year: null,
    container_title: 'Pharmacie Globale International Journal',
    doi: null,
    url: null,
    axis_primary_code: 'N1 Tabac: ethnobotanique & rituels',
    notes: 'Méthodes d\'extraction des huiles aromatiques : distillation à la vapeur, extraction par solvant, enfleurage, expression à froid, CO2 supercritique. Histoire de l\'enfleurage (Grasse, 1860). Taxonomie complète des méthodes avec paramètres (température, solvant, rendement, distorsion aromatique).',
    tags: JSON.stringify(['extraction', 'huiles essentielles', 'enfleurage', 'distillation', 'CO2 supercritique', 'Grasse', 'méthodes d\'extraction']),
    relevance_score: 4,
    read_status: 'read',
    pack_version: 'batch3'
  },
];

console.log(`Insertion de ${references.length} nouvelles références...`);

let inserted = 0;
let skipped = 0;

for (const ref of references) {
  // Vérifier si la référence existe déjà
  const [existing] = await conn.execute('SELECT id FROM v3_references WHERE entry_key = ?', [ref.entry_key]);
  if (existing.length > 0) {
    console.log(`SKIP (déjà présent): ${ref.entry_key}`);
    skipped++;
    continue;
  }
  
  await conn.execute(
    `INSERT INTO v3_references 
     (entry_key, entry_type, title, authors, year, container_title, doi, url, axis_primary_code, notes, tags, relevance_score, read_status, pack_version, imported_at, updated_at)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NOW(), NOW())`,
    [
      ref.entry_key,
      ref.entry_type,
      ref.title,
      ref.authors,
      ref.year || null,
      ref.container_title,
      ref.doi || null,
      ref.url || null,
      ref.axis_primary_code,
      ref.notes,
      ref.tags,
      ref.relevance_score,
      ref.read_status,
      ref.pack_version
    ]
  );
  console.log(`OK: ${ref.entry_key}`);
  inserted++;
}

console.log(`\n=== RÉSULTAT ===`);
console.log(`Insérées : ${inserted}`);
console.log(`Ignorées (doublons) : ${skipped}`);

const [total] = await conn.execute('SELECT COUNT(*) as cnt FROM v3_references');
console.log(`Total v3_references : ${total[0].cnt}`);

await conn.end();
