DROP TABLE `accord_civilisations`;--> statement-breakpoint
DROP TABLE `accords`;--> statement-breakpoint
DROP TABLE `civilisations`;--> statement-breakpoint
DROP TABLE `families`;--> statement-breakpoint
DROP TABLE `installation_families`;--> statement-breakpoint
DROP TABLE `installation_recettes`;--> statement-breakpoint
DROP TABLE `installations`;--> statement-breakpoint
DROP TABLE `laboratoire`;--> statement-breakpoint
DROP TABLE `laboratoire_molecules`;--> statement-breakpoint
DROP TABLE `laboratoire_recettes`;--> statement-breakpoint
DROP TABLE `molecule_accords`;--> statement-breakpoint
DROP TABLE `molecule_families`;--> statement-breakpoint
DROP TABLE `molecule_recettes`;--> statement-breakpoint
DROP TABLE `molecules`;--> statement-breakpoint
DROP TABLE `petrichor`;--> statement-breakpoint
DROP TABLE `petrichor_molecules`;--> statement-breakpoint
DROP TABLE `petrichor_recettes`;--> statement-breakpoint
DROP TABLE `petrichor_tabacs`;--> statement-breakpoint
DROP TABLE `prototype_laboratoire`;--> statement-breakpoint
DROP TABLE `prototype_molecules`;--> statement-breakpoint
DROP TABLE `prototypes`;--> statement-breakpoint
DROP TABLE `recettes`;--> statement-breakpoint
DROP TABLE `tabac_accords`;--> statement-breakpoint
DROP TABLE `tabac_civilisations`;--> statement-breakpoint
DROP TABLE `tabac_molecules`;--> statement-breakpoint
DROP TABLE `tabacs`;--> statement-breakpoint
DROP TABLE `volcanique`;--> statement-breakpoint
DROP TABLE `volcanique_molecules`;--> statement-breakpoint
DROP TABLE `volcanique_recettes`;--> statement-breakpoint
DROP TABLE `volcanique_tabacs`;