CREATE TABLE `extended_supplier_materials` (
	`id` int AUTO_INCREMENT NOT NULL,
	`supplier_id` int NOT NULL,
	`plant_id` int,
	`variety_id` int,
	`terroir_id` int,
	`product_name` varchar(255) NOT NULL,
	`product_type` varchar(100),
	`price_per_kg` decimal(10,2),
	`currency` varchar(3) DEFAULT 'EUR',
	`price_date` timestamp,
	`availability` enum('in_stock','on_order','seasonal','limited','discontinued','unknown') DEFAULT 'unknown',
	`minimum_quantity` varchar(50),
	`quality_grade` varchar(50),
	`certifications` json,
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `extended_supplier_materials_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `extended_suppliers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`supplier_id` varchar(30) NOT NULL,
	`name` varchar(255) NOT NULL,
	`legal_name` varchar(255),
	`supplier_type` enum('producer','distiller','trader','cooperative','laboratory','broker','other') NOT NULL,
	`country` varchar(100),
	`address` text,
	`phone` varchar(50),
	`email` varchar(255),
	`website` varchar(500),
	`contact_person` varchar(255),
	`specialties` json,
	`main_products` json,
	`certifications` json,
	`minimum_order` varchar(100),
	`lead_time` varchar(100),
	`payment_terms` varchar(255),
	`shipping_methods` json,
	`quality_rating` enum('excellent','good','acceptable','poor','not_rated') DEFAULT 'not_rated',
	`reliability_rating` enum('excellent','good','acceptable','poor','not_rated') DEFAULT 'not_rated',
	`price_rating` enum('premium','competitive','standard','budget','not_rated') DEFAULT 'not_rated',
	`first_order_date` timestamp,
	`last_order_date` timestamp,
	`total_orders` int DEFAULT 0,
	`status` enum('active','inactive','blacklisted','prospect') DEFAULT 'active',
	`notes` text,
	`internal_notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `extended_suppliers_id` PRIMARY KEY(`id`),
	CONSTRAINT `extended_suppliers_supplier_id_unique` UNIQUE(`supplier_id`)
);
--> statement-breakpoint
CREATE TABLE `extraction_methods` (
	`id` int AUTO_INCREMENT NOT NULL,
	`method_id` varchar(30) NOT NULL,
	`name` varchar(255) NOT NULL,
	`short_name` varchar(50),
	`category` enum('distillation','expression','extraction_solvant','co2_supercritique','enfleurage','maceration','hydrodistillation','percolation','other') NOT NULL,
	`description` text,
	`principle` text,
	`parameters` json,
	`equipment` json,
	`typical_yields` json,
	`molecular_impact` text,
	`preserved_molecules` json,
	`degraded_molecules` json,
	`advantages` json,
	`disadvantages` json,
	`best_for` json,
	`not_recommended_for` json,
	`cost_level` enum('low','medium','high','very_high') DEFAULT 'medium',
	`complexity_level` enum('simple','moderate','complex','expert') DEFAULT 'moderate',
	`notes` text,
	`references` json,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `extraction_methods_id` PRIMARY KEY(`id`),
	CONSTRAINT `extraction_methods_method_id_unique` UNIQUE(`method_id`)
);
--> statement-breakpoint
CREATE TABLE `plant_analyses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`analysis_id` varchar(30) NOT NULL,
	`plant_id` int,
	`variety_id` int,
	`sample_id` int,
	`analysis_date` timestamp,
	`laboratory` varchar(255),
	`analyst` varchar(255),
	`method` enum('gc_ms','gc_fid','hplc','nmr','ir','other') DEFAULT 'gc_ms',
	`conditions` json,
	`molecular_profile` json,
	`total_compounds_identified` int,
	`major_compounds` json,
	`olfactive_classification` json,
	`quality_score` enum('excellent','good','acceptable','poor','invalid') DEFAULT 'good',
	`quality_notes` text,
	`raw_data_url` varchar(500),
	`report_url` varchar(500),
	`chromatogram_url` varchar(500),
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `plant_analyses_id` PRIMARY KEY(`id`),
	CONSTRAINT `plant_analyses_analysis_id_unique` UNIQUE(`analysis_id`)
);
--> statement-breakpoint
CREATE TABLE `plant_extractions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`plant_id` int NOT NULL,
	`extraction_method_id` int NOT NULL,
	`plant_part` varchar(100),
	`yield_percent` decimal(5,3),
	`yield_notes` text,
	`product_type` varchar(100),
	`product_quality` text,
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `plant_extractions_id` PRIMARY KEY(`id`),
	CONSTRAINT `unique_plant_extraction` UNIQUE(`plant_id`,`extraction_method_id`)
);
--> statement-breakpoint
CREATE TABLE `plant_samples` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sample_id` varchar(30) NOT NULL,
	`batch_number` varchar(50),
	`plant_id` int NOT NULL,
	`variety_id` int,
	`terroir_id` int,
	`supplier_id` int,
	`harvest_date` timestamp,
	`harvest_year` int,
	`harvest_location` varchar(255),
	`harvest_method` varchar(100),
	`plant_part` enum('feuille','fleur','fruit','graine','racine','ecorce','bois','resine','plante_entiere','autre') DEFAULT 'feuille',
	`botanical_state` varchar(50),
	`processing_method` varchar(255),
	`processing_date` timestamp,
	`extraction_method_id` int,
	`initial_quantity` varchar(50),
	`current_quantity` varchar(50),
	`unit` varchar(20),
	`storage_location` varchar(255),
	`storage_conditions` json,
	`expiration_date` timestamp,
	`quality_grade` enum('premium','standard','economy','research','expired','unknown') DEFAULT 'unknown',
	`quality_notes` text,
	`certifications` json,
	`purchase_price` decimal(10,2),
	`currency` varchar(3) DEFAULT 'EUR',
	`price_per_unit` decimal(10,2),
	`status` enum('available','reserved','in_use','depleted','expired','disposed') DEFAULT 'available',
	`notes` text,
	`image_url` varchar(500),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `plant_samples_id` PRIMARY KEY(`id`),
	CONSTRAINT `plant_samples_sample_id_unique` UNIQUE(`sample_id`)
);
--> statement-breakpoint
CREATE TABLE `plant_terroirs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`plant_id` int NOT NULL,
	`terroir_id` int NOT NULL,
	`local_name` varchar(255),
	`cultivation_start` int,
	`annual_production` varchar(100),
	`quality_notes` text,
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `plant_terroirs_id` PRIMARY KEY(`id`),
	CONSTRAINT `unique_plant_terroir` UNIQUE(`plant_id`,`terroir_id`)
);
--> statement-breakpoint
CREATE TABLE `plant_varieties` (
	`id` int AUTO_INCREMENT NOT NULL,
	`variety_id` varchar(30) NOT NULL,
	`plant_id` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`latin_name` varchar(255),
	`variety_type` enum('cultivar','chemotype','landrace','hybrid','clone','wild','other') NOT NULL,
	`breeder` varchar(255),
	`year_registered` int,
	`country_of_origin` varchar(100),
	`parent_varieties` json,
	`distinctive_features` text,
	`morphology` json,
	`dominant_molecules` json,
	`molecular_profile` json,
	`olfactive_description` text,
	`olfactive_notes` json,
	`yield_per_hectare` varchar(50),
	`essential_oil_yield` varchar(50),
	`harvest_period` varchar(100),
	`optimal_harvest_stage` varchar(100),
	`commercial_availability` enum('widely_available','limited','rare','research_only','extinct','unknown') DEFAULT 'unknown',
	`suppliers` json,
	`notes` text,
	`references` json,
	`image_url` varchar(500),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `plant_varieties_id` PRIMARY KEY(`id`),
	CONSTRAINT `plant_varieties_variety_id_unique` UNIQUE(`variety_id`)
);
--> statement-breakpoint
CREATE TABLE `terroirs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`terroir_id` varchar(30) NOT NULL,
	`name` varchar(255) NOT NULL,
	`country` varchar(100) NOT NULL,
	`region` varchar(255),
	`sub_region` varchar(255),
	`latitude` decimal(10,7),
	`longitude` decimal(10,7),
	`altitude` varchar(50),
	`climate_type` enum('tropical','subtropical','mediterranean','oceanic','continental','arid','semi_arid','alpine','equatorial','other'),
	`avg_temperature` varchar(50),
	`annual_rainfall` varchar(50),
	`humidity` varchar(50),
	`soil_type` enum('clay','sandy','loamy','chalky','volcanic','alluvial','peaty','rocky','mixed','other'),
	`soil_ph` varchar(20),
	`soil_characteristics` text,
	`main_crops` json,
	`production_history` text,
	`annual_production` varchar(100),
	`certifications` json,
	`quality_rating` enum('exceptional','excellent','good','standard','variable','unknown') DEFAULT 'unknown',
	`reputation` text,
	`notes` text,
	`image_url` varchar(500),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `terroirs_id` PRIMARY KEY(`id`),
	CONSTRAINT `terroirs_terroir_id_unique` UNIQUE(`terroir_id`)
);
