DROP TABLE `absorbe_profiles`;--> statement-breakpoint
DROP TABLE `accord_civilisations`;--> statement-breakpoint
DROP TABLE `accords`;--> statement-breakpoint
DROP TABLE `analytics_events`;--> statement-breakpoint
DROP TABLE `bibliographie`;--> statement-breakpoint
DROP TABLE `bibliographie_molecules`;--> statement-breakpoint
DROP TABLE `chemical_families`;--> statement-breakpoint
DROP TABLE `citations`;--> statement-breakpoint
DROP TABLE `traditions_olfactives`;--> statement-breakpoint
DROP TABLE `climate_studies`;--> statement-breakpoint
DROP TABLE `experimental_accord_civilisations`;--> statement-breakpoint
DROP TABLE `experimental_accords`;--> statement-breakpoint
DROP TABLE `extraction_tests`;--> statement-breakpoint
DROP TABLE `families`;--> statement-breakpoint
DROP TABLE `field_archives`;--> statement-breakpoint
DROP TABLE `gestion_agenda`;--> statement-breakpoint
DROP TABLE `gestion_budget`;--> statement-breakpoint
DROP TABLE `gestion_mentorat`;--> statement-breakpoint
DROP TABLE `glossary`;--> statement-breakpoint
DROP TABLE `installation_families`;--> statement-breakpoint
DROP TABLE `installation_recettes`;--> statement-breakpoint
DROP TABLE `installations`;--> statement-breakpoint
DROP TABLE `laboratoire`;--> statement-breakpoint
DROP TABLE `laboratoire_molecules`;--> statement-breakpoint
DROP TABLE `laboratoire_recettes`;--> statement-breakpoint
DROP TABLE `milestones`;--> statement-breakpoint
DROP TABLE `modification_history`;--> statement-breakpoint
DROP TABLE `molecular_protocols`;--> statement-breakpoint
DROP TABLE `molecule_accords`;--> statement-breakpoint
DROP TABLE `molecule_chemical_families`;--> statement-breakpoint
DROP TABLE `molecule_families`;--> statement-breakpoint
DROP TABLE `molecule_notes`;--> statement-breakpoint
DROP TABLE `molecule_synergies`;--> statement-breakpoint
DROP TABLE `molecules`;--> statement-breakpoint
DROP TABLE `molecules_recettes`;--> statement-breakpoint
DROP TABLE `petrichor`;--> statement-breakpoint
DROP TABLE `petrichor_experimental_accords`;--> statement-breakpoint
DROP TABLE `petrichor_molecules`;--> statement-breakpoint
DROP TABLE `petrichor_recettes`;--> statement-breakpoint
DROP TABLE `petrichor_tabacs`;--> statement-breakpoint
DROP TABLE `projet_accords`;--> statement-breakpoint
DROP TABLE `projet_field_archives`;--> statement-breakpoint
DROP TABLE `projet_molecules`;--> statement-breakpoint
DROP TABLE `projet_recettes`;--> statement-breakpoint
DROP TABLE `projets_artistiques`;--> statement-breakpoint
DROP TABLE `prototype_chemical_families`;--> statement-breakpoint
DROP TABLE `prototype_laboratoire`;--> statement-breakpoint
DROP TABLE `prototype_molecules`;--> statement-breakpoint
DROP TABLE `prototypes`;--> statement-breakpoint
DROP TABLE `recette_molecules`;--> statement-breakpoint
DROP TABLE `recette_tabac_associations`;--> statement-breakpoint
DROP TABLE `recettes`;--> statement-breakpoint
DROP TABLE `recettes_formules_reference`;--> statement-breakpoint
DROP TABLE `recherche_radicale`;--> statement-breakpoint
DROP TABLE `recipe_versions`;--> statement-breakpoint
DROP TABLE `research_timeline`;--> statement-breakpoint
DROP TABLE `saved_formulas`;--> statement-breakpoint
DROP TABLE `sensory_scales`;--> statement-breakpoint
DROP TABLE `shared_collections`;--> statement-breakpoint
DROP TABLE `situated_smells`;--> statement-breakpoint
DROP TABLE `supplier_materials`;--> statement-breakpoint
DROP TABLE `suppliers`;--> statement-breakpoint
DROP TABLE `synergies`;--> statement-breakpoint
DROP TABLE `tabac_accords`;--> statement-breakpoint
DROP TABLE `tabac_civilisations`;--> statement-breakpoint
DROP TABLE `tabac_molecules`;--> statement-breakpoint
DROP TABLE `tabacs`;--> statement-breakpoint
DROP TABLE `tasting_notes`;--> statement-breakpoint
DROP TABLE `terpene_synergies`;--> statement-breakpoint
DROP TABLE `tobacco_formula_installations`;--> statement-breakpoint
DROP TABLE `tobacco_formulas`;--> statement-breakpoint
DROP TABLE `user_favorites`;--> statement-breakpoint
DROP TABLE `user_notes`;--> statement-breakpoint
DROP TABLE `volcanique`;--> statement-breakpoint
DROP TABLE `volcanique_experimental_accords`;--> statement-breakpoint
DROP TABLE `volcanique_molecules`;--> statement-breakpoint
DROP TABLE `volcanique_recettes`;--> statement-breakpoint
DROP TABLE `volcanique_tabacs`;