import { loadExport, setupCanvas, drawFooter, downloadCsv, nowEvent } from "../shared.js";
const canvas=document.querySelector("#canvas"), context=setupCanvas(canvas), events=[]; let data=await loadExport(), distance=80, port, reader, keepReading=false;
const distanceEl=document.querySelector("#distance"), status=document.querySelector("#status");
function render(){ const width=canvas.getBoundingClientRect().width,height=canvas.getBoundingClientRect().height; const proximity=1-Math.min(1,Math.max(0,(distance-10)/190)); context.fillStyle="#030712";context.fillRect(0,0,width,height); const center={x:width/2,y:height/2}; const orbit=220-(proximity*130); context.globalAlpha=.32+.68*proximity; data.molecules.forEach((m,i)=>{const a=(Math.PI*2*i)/data.molecules.length-Math.PI/2;const x=center.x+Math.cos(a)*orbit,y=center.y+Math.sin(a)*orbit;context.strokeStyle="#526fdd";context.lineWidth=1+proximity*3;context.beginPath();context.moveTo(center.x,center.y);context.lineTo(x,y);context.stroke();context.fillStyle=`hsl(${190+i*18} 90% ${55+proximity*20}%)`;context.beginPath();context.arc(x,y,7+m.intensity*.09+proximity*6,0,Math.PI*2);context.fill();context.globalAlpha=1;context.fillStyle="#e5efff";context.font="12px Noto Sans";context.fillText(m.name,x+12,y+4);context.globalAlpha=.32+.68*proximity;});context.globalAlpha=1;context.fillStyle="#f0f6ff";context.beginPath();context.arc(center.x,center.y,20+proximity*30,0,Math.PI*2);context.fill();context.fillStyle="#091226";context.font="700 12px Noto Sans";context.fillText(`${Math.round(distance)} cm`,center.x-18,center.y+4);drawFooter(context,width,height,data); }
function setDistance(value, source){ const parsed=Number(value); if(!Number.isFinite(parsed)||parsed<0||parsed>1000)return;distance=parsed;distanceEl.textContent=`${source} · ${Math.round(distance)} cm`;render();}
document.querySelector("#simulate").oninput=e=>setDistance(e.target.value,"Simulation");
document.querySelector("#log").onclick=()=>{events.push(nowEvent("graphe_proximite","distance",distance,"cm","Source affichée : Arduino ou simulation"));alert("Valeur ajoutée au journal local.");};document.querySelector("#download").onclick=()=>downloadCsv(events,"perfumum-graphe-proximite.csv");
async function readLoop(){const decoder=new TextDecoderStream();const closed=port.readable.pipeTo(decoder.writable);reader=decoder.readable.getReader();let buffer="";try{while(keepReading){const {value,done}=await reader.read();if(done)break;buffer+=value;const lines=buffer.split(/\r?\n/);buffer=lines.pop();lines.forEach(line=>setDistance(line.trim(),"Arduino"));}}catch(error){status.textContent=`Lecture interrompue : ${error.message}`;}finally{reader.releaseLock();await closed.catch(()=>{});}}
document.querySelector("#connect").onclick=async()=>{if(!("serial" in navigator)){status.textContent="Web Serial indisponible : utilisez Chromium sur ordinateur ou la simulation.";return;}try{port=await navigator.serial.requestPort();await port.open({baudRate:9600});keepReading=true;status.textContent="Arduino connecté en lecture seule à 9 600 bauds.";readLoop();}catch(error){status.textContent=`Connexion annulée ou échouée : ${error.message}`;}};
document.querySelector("#disconnect").onclick=async()=>{keepReading=false;if(reader)await reader.cancel().catch(()=>{});if(port)await port.close().catch(()=>{});status.textContent="Port fermé.";};
render();
