-- Script d'enrichissement du glossaire PERFUMUM
-- Ajout de termes scientifiques fondamentaux

-- Termes de chimie des parfums
INSERT IGNORE INTO glossary (term, definition, category, examples, related_terms) VALUES
('Numéro CAS', 'Identifiant numérique unique attribué par le Chemical Abstracts Service à chaque substance chimique. Format: XXX-XX-X. Permet une identification sans ambiguïté des molécules à l''échelle internationale.', 'chimie', 'Linalol: 78-70-6, Limonène: 138-86-3, Géosmine: 19700-21-1', 'IUPAC, Formule chimique'),
('Nomenclature IUPAC', 'Système de dénomination systématique des composés chimiques établi par l''Union internationale de chimie pure et appliquée. Permet de déduire la structure moléculaire à partir du nom.', 'chimie', '3,7-dimethylocta-1,6-dien-3-ol (linalol)', 'CAS, Formule chimique'),
('Monoterpène', 'Terpène composé de deux unités isoprène (C10H16). Constituants majeurs des huiles essentielles, très volatils et responsables des notes de tête.', 'molecule', 'Limonène, Pinène, Myrcène, Terpinène', 'Sesquiterpène, Diterpène, Terpène'),
('Sesquiterpène', 'Terpène composé de trois unités isoprène (C15H24). Moins volatils que les monoterpènes, ils contribuent aux notes de cœur et de fond.', 'molecule', 'Caryophyllène, Humulène, Farnesène', 'Monoterpène, Diterpène, Terpène'),
('Diterpène', 'Terpène composé de quatre unités isoprène (C20H32). Molécules lourdes, peu volatiles, utilisées comme fixateurs.', 'molecule', 'Phytol, Rétinol, Taxol', 'Monoterpène, Sesquiterpène'),
('Point d''ébullition', 'Température à laquelle une substance passe de l''état liquide à l''état gazeux. Indicateur clé de la volatilité d''une molécule olfactive.', 'propriete', 'Linalol: 196°C, Limonène: 176°C, Ambroxan: 310°C', 'Volatilité, Pression de vapeur'),
('Masse moléculaire', 'Somme des masses atomiques de tous les atomes constituant une molécule, exprimée en g/mol. Influence la volatilité et la diffusion.', 'propriete', 'Linalol: 154 g/mol, Limonène: 136 g/mol', 'Formule chimique, Volatilité'),
('LogP', 'Coefficient de partage octanol/eau. Mesure la lipophilie d''une molécule. Un LogP élevé indique une affinité pour les phases huileuses.', 'propriete', 'Limonène: 4.5, Linalol: 2.9', 'Solubilité, Lipophilie'),
('Aldéhyde', 'Composé organique contenant un groupe fonctionnel -CHO. Les aldéhydes apportent des notes fraîches, vertes ou grasses selon leur structure.', 'chimie', 'Citral, Citronellal, Aldéhyde C-11', 'Cétone, Alcool'),
('Cétone', 'Composé organique contenant un groupe fonctionnel C=O lié à deux carbones. Les cétones apportent souvent des notes mentholées ou camphrées.', 'chimie', 'Carvone, Menthone, Ionone', 'Aldéhyde, Alcool'),
('Ester', 'Composé formé par réaction entre un acide et un alcool. Les esters apportent des notes fruitées, florales ou balsamiques.', 'chimie', 'Acétate de linalyle, Acétate de géranyle, Salicylate de benzyle', 'Alcool, Acide'),
('Phénol', 'Composé aromatique hydroxylé. Les phénols apportent des notes épicées, médicinales ou fumées.', 'chimie', 'Eugénol, Thymol, Carvacrol', 'Aromatique, Alcool'),
('Volatilité', 'Capacité d''une substance à passer à l''état gazeux. Détermine la vitesse de diffusion et la persistance d''une note olfactive.', 'propriete', 'Notes de tête: haute volatilité, Notes de fond: basse volatilité', 'Point d''ébullition, Pression de vapeur'),
('Intensité olfactive', 'Puissance perçue d''une odeur à une concentration donnée. Varie selon le seuil de perception de chaque molécule.', 'propriete', 'Géosmine: très intense (seuil 0.1 ppb), Limonène: modérée', 'Seuil de perception, Diffusion'),
('Seuil de perception', 'Concentration minimale à laquelle une odeur devient détectable. Exprimé en ppm, ppb ou ng/L.', 'propriete', 'Géosmine: 0.1 ppb, Vanilline: 20 ppb', 'Intensité olfactive'),
('Hydrodistillation', 'Méthode d''extraction des huiles essentielles par entraînement à la vapeur d''eau. Technique traditionnelle préservant l''intégrité des composés thermosensibles.', 'extraction', 'Huile essentielle de lavande, Rose de Damas', 'Distillation, Extraction CO2'),
('Extraction CO2 supercritique', 'Technique d''extraction utilisant le CO2 à l''état supercritique comme solvant. Produit des extraits de haute qualité sans résidus de solvant.', 'extraction', 'Absolue de jasmin, Extrait de vanille', 'Hydrodistillation, Enfleurage'),
('Enfleurage', 'Technique traditionnelle d''extraction des parfums floraux par absorption dans des corps gras. Utilisée pour les fleurs fragiles.', 'extraction', 'Jasmin, Tubéreuse, Fleur d''oranger', 'Hydrodistillation, Macération'),
('Macération', 'Extraction par trempage prolongé dans un solvant (alcool, huile). Permet d''extraire les composés aromatiques des matières sèches.', 'extraction', 'Teinture de benjoin, Macérat de vanille', 'Enfleurage, Infusion'),
('Accord olfactif', 'Combinaison harmonieuse de plusieurs matières premières créant une impression olfactive nouvelle et cohérente.', 'formulation', 'Accord fougère, Accord chypre, Accord oriental', 'Pyramide olfactive, Harmonie'),
('Pyramide olfactive', 'Structure classique d''un parfum en trois niveaux: notes de tête (volatiles), notes de cœur (moyennes), notes de fond (persistantes).', 'formulation', 'Tête: agrumes, Cœur: floraux, Fond: boisés', 'Accord, Évolution'),
('Fixateur', 'Substance peu volatile qui ralentit l''évaporation des notes plus légères et prolonge la tenue du parfum.', 'formulation', 'Ambroxan, Muscs, Résines', 'Volatilité, Persistance'),
('Synergie moléculaire', 'Interaction entre molécules produisant un effet supérieur à la somme des effets individuels.', 'interaction', 'Effet entourage des terpènes, Potentialisation', 'Antagonisme, Additivité'),
('Réaction de Maillard', 'Réaction chimique entre sucres et acides aminés produisant des composés aromatiques bruns. Responsable des odeurs de torréfaction.', 'reaction', 'Café torréfié, Pain grillé, Caramel', 'Pyrolyse, Caramélisation'),
('Oxydation', 'Réaction chimique avec l''oxygène modifiant les propriétés olfactives. Peut améliorer ou dégrader un parfum selon les cas.', 'reaction', 'Vieillissement des agrumes, Rancissement', 'Réduction, Dégradation'),
('Chromatographie', 'Technique analytique de séparation des composés d''un mélange. Essentielle pour identifier les constituants des huiles essentielles.', 'technique', 'GC-MS (chromatographie gazeuse couplée à la spectrométrie de masse)', 'Spectrométrie, Analyse'),
('Spectrométrie de masse', 'Technique d''identification des molécules par mesure de leur rapport masse/charge. Permet l''identification précise des composés.', 'technique', 'Identification des terpènes, Détection des adultérations', 'Chromatographie, Analyse'),
('Olfactométrie', 'Mesure scientifique des propriétés olfactives. Combine analyse instrumentale et évaluation sensorielle.', 'technique', 'GC-Olfactométrie, Panel sensoriel', 'Analyse sensorielle, Chromatographie'),
('Headspace', 'Technique d''analyse des composés volatils dans l''espace au-dessus d''un échantillon. Reproduit la perception olfactive naturelle.', 'technique', 'Analyse de fleurs fraîches, Étude de l''environnement', 'Chromatographie, Volatilité');

